theme: jekyll-theme-minimal
title: [Kyler Kanegawa]
description: BSc in Microbiology and Immunology at the University of British Columbia ![image](https://github.com/kylerkanegawa/kylerkanegawa.github.io/blob/master/20180312_130823.jpg)
